-- Add stat columns to players table
-- Hitter stat columns
ALTER TABLE players ADD COLUMN IF NOT EXISTS g NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS pa NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ab NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS h NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS doubles NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS triples NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS hr NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS runs NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS rbi NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS bb NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS so NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS hbp NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS sb NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS cs NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS avg NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS obp NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS slg NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ops NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS woba NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS wrc_plus NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS bsr NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS fld NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS off NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS def NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS war NUMERIC;

-- Pitcher stat columns
ALTER TABLE players ADD COLUMN IF NOT EXISTS gs NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ip NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS w NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS l NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS qs NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS sv NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS hld NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS er NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS whip NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS k_per_9 NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS bb_per_9 NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS era NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS fip NUMERIC;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ra9_war NUMERIC;

-- Create import_history table
CREATE TABLE IF NOT EXISTS import_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_type TEXT NOT NULL CHECK (import_type IN ('hitter_projections', 'pitcher_projections', 'auction_values')),
  filename TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW(),
  rows_processed INTEGER,
  rows_successful INTEGER
);

-- Create indexes for import_history
CREATE INDEX IF NOT EXISTS idx_import_history_type ON import_history(import_type);
CREATE INDEX IF NOT EXISTS idx_import_history_uploaded_at ON import_history(uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_history_type_uploaded ON import_history(import_type, uploaded_at DESC);

-- Enable Row Level Security
ALTER TABLE import_history ENABLE ROW LEVEL SECURITY;

-- Drop existing policy if it exists (to avoid conflicts)
DROP POLICY IF EXISTS "Allow all operations on import_history" ON import_history;

-- Create policy (allow all for now - adjust based on auth needs)
CREATE POLICY "Allow all operations on import_history" ON import_history FOR ALL USING (true) WITH CHECK (true);

